### ISSUE TITLE
Improved Grammar: Statements in MathMatrixValueExplicitExpression

### ISSUE THREAD

**Issue by ChristophRichter92** [EmbeddedMontiArc/MontiMath#31]
Currently the ";" is interpreted as Statement. Should be interpreted as MathMatrixValueExplicitExpression 
according to 
```
MathMatrixValueExplicitExpression implements Expression<220> =
      "[" (MathMatrixAccessExpression || ";")* "]"
    ;
```

Corresponding expression 
`Statement implements Expression<5> = Expression ";" ; // to not write down every time ";"?`
from
https://github.com/EmbeddedMontiArc/MontiMath/blob/nina-improve_grammar/src/main/grammars/de/monticore/lang/Math.mc4

**Comment by ChristophRichter92** [comment]
`[1, 1; 1 1]` creates the following AST equal to [1, 1, 1, 1] because the ; is consumed by Statement. Maybe similar to #30 but with ; instead of whitespace. 

![image](https://user-images.githubusercontent.com/4721248/40330967-0da03a22-5d4f-11e8-96c0-73f3e6bf0fc3.png)

**Comment by ChristophRichter92** [comment]
Any idea how to fix this?

**Comment by vonwenckstern** [comment]
https://github.com/EmbeddedMontiArc/MontiMath/issues/31#issuecomment-390789491 it is not similar to  the whitespace problem, as the whitespaces are thrown away by MontiCore and the semicolon must be explicitely modeled.

The problem is in the following line
```
Statement implements Expression<5> = Expression ";" ; // to not write down every time ";"?
```

A `statement` should not be an `Expression`, so the `implements Expression` must be removed.
A `statement` should be its own interface but with no priority:
```
interface Statement;
```

**Comment by ChristophRichter92** [comment]
I agree on the problem. 

If it does not implement Expression anymore `";"?` has to be inserted on a few expressions. 

Then `Statement` is not used anymore and can be removed from the grammar. If it is a interface it has to be removed. 

=> I remove it

**Comment by vonwenckstern** [comment]
@ChristophRichter92 you should not remove the `statement` from the grammar.
You need to refactor the grammar so that the rules use statements where it is needed and expression otherwise.

Take a look at the JavaDSL: https://github.com/MontiCore/javaDSL/blob/master/src/main/grammars/de/monticore/java/JavaDSL.mc4#L222

There is also the `statement` rule.

And the `if` statement is implemented in the following way:
```
IfStatement implements Statement
    =   "if" "(" condition:Expression ")" thenStatement:Statement ("else" elseStatement:Statement)?
 ;
```

You need to do it the same way in MontiMath.

**For the next questions please ask Evgeny directly as he is your superviser -- he will answer you all the questions about MontiCore.**

And please add the `statement` rule to the grammar again, thank you.
